<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class MarrigeCertifications extends Model
{
    //
     protected $table = 'marriage';
      protected $fillable=[
      	       'reg_no_nep',
'form_no_nep',
'reg_date_nep',
'applicant_name_nep',
'wife_name_nep',
'grand_father_name_nep',
'father_name_nep',
'applicant_age_nep',
'husband_name_nep',
'girls_grand_father_name_nep',
'girls_father_name_nep',
'girls_provience_nep',
'girls_district_nep',
'girls_local_state_nep',
'lc_type',
'girls_ward_no_nep',
'girls_age_nep',
'girls_name_nep',
'date_bs_nep',
'date_ad_nep',
'bride_citizen_no_nep',
'bride_citizen_issued_date_nep',
'bride_citizen_issued_district_nep',
'bridegroom_citizen_no_nep',
'bridegroom_citizen_issued_date_nep',
'bridegroom_citizen_issued_district_nep',
'local_registrar_name_nep',
'signed_date_nep',
'reg_no',
'form_no',
'reg_date',
'applicant_name',
'wife_name',
'husband_name',
'husband_age',
'father_name',
'grand_father_name',
'girls_name',
'girls_age',
'girls_father_name',
'girls_grand_father_name',
'girls_ward_no',
'girls_local_state',
'lc_type_english',
'girls_district',
'girls_provience',
'date_bs',
'date_ad',
'bride_citizen_issued_date',
'bride_citizen_issued_district',
'bride_citizen_no',
'bridegroom_citizen_issued_date',
'bridegroom_citizen_issued_district',
'bridegroom_citizen_no',
'local_registrar_name',
'signed_date',
'nibedak_name',
'nibedak_address',
'nibedak_citizenship_no',
'nibedak_nid',
'user_id',
'marriage_type_np',
'marriage_type_en',
'bridegroom_dob_np',
'bridegroom_dob_en',
'bride_dob_np',
'bride_dob_en',
'bridegroom_address_np',
'bridegroom_address_en',
'bride_address_np',
'bride_address_en',
'bridegroom_mother_name_np',
'bridegroom_mother_name_en',
'bride_mother_name_np',
'bride_mother_name_en'

      ];
}
